### ISSUE TITLE
[BUG] Background notifications are not catched

### ISSUE THREAD

**Issue by twittemb** [Azure/azure-notificationhubs-ios#100]
**Describe the bug**
I'm integrating Azure Notification Hubs in an iOS app. I use the azure notification hub portal to send a notification to my app.
While the app is in foreground the notification is received and the function "func notificationHub(didReceivePushNotification:)" is called. I'm able to read the payload.
But while the app is in background, the notification is displayed by the OS as a banner, when I click on it, then the app is put back to foreground but the function "func notificationHub(didReceivePushNotification:)" is never called. 

I've tried with the SwiftUI sample app, and I have the same behaviour.

Could this be because of the Token based authentication to the APNs ?
Is the Test Send function able to send background notifications ?

***Exception or Stack Trace***
The first time I click on the banner (log from the sample app):
```
2020-09-23 16:48:40.186513-0400 SampleNHAppSwiftUI[6769:2781293] [connection] nw_read_request_report [C1] Receive failed with error "Software caused connection abort"
```

**To Reproduce**
- Go to Azure notification Hub portal / Test Send
- pick Apple for the platforms
- leave the payload as is
- send the notification
- the notification is sent and received 

***Code Snippet***
in the AppDelegate:
```
MSNotificationHub.start(connectionString: connectionString, hubName: hubName)
```

in the SceneDelegate
```
MSNotificationHub.setDelegate(self)
MSNotificationHub.setLifecycleDelegate(self)

...

func notificationHub(_ notificationHub: MSNotificationHub!, didReceivePushNotification message: MSNotificationHubMessage!) {
    NSLog("Received notification: %@; %@", message.title ?? "<nil>", message.body ?? "<nil>")
}
```

**Expected behavior**
While in background, the notification is displayed as a banner. When the banner is clicked, the app is put in foreground and the notification payload is accessible in the function "func notificationHub(didReceivePushNotification:)"

**Screenshots**

**Setup (please complete the following information):**
 - OS: iOS 14
 - IDE : Xcode 12
 - Version of the Library used: 3.1.1
 - the method swizzling is still activated
 -  I'm using a Token based authentication with the APNs (not a Certificate method)

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

[UPDATE]

The only way I can make it work is by making the AppDelegate conform to `UNUserNotificationCenterDelegate` and call `UNUserNotificationCenter.current().delegate = self` before starting `MSNotificationHub.start`

Do you confirm ?

**Comment by mpodwysocki** [comment]
@twittemb to confirm, have you enabled `Background Modes` and `Remote Notifications` as noted in the [Pushing Background Updates to Your App]?(https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app)

**Comment by twittemb** [comment]
@mpodwysocki 

Yes. In fact I have done my tests with the SwiftUI sample app (adapted to my notification hubs data).

I have remade the test this morning and If I don't add the UNUserNotificationCenterDelegate conformance and the delegation in the AppDelegate, then background notifications are not read in the application.

Once I add that, I have foreground and background notifications (for silent notifications as well as alert notifications)

**Comment by mpodwysocki** [comment]
@twittemb will investigate the other scenarios.  The test send I believe does not do the proper APNS headers for content-available which is required here.

> Additionally, the notification’s POST request should contain the apns-push-type header field with a value of background, and the apns-priority field with a value of 5. The APNs server requires the apns-push-type field when sending push notifications to Apple Watch, and recommends it for all platforms. For more information, see Create and Send a POST Request to APNs.

**Comment by twittemb** [comment]
I guess there might be an issue with the swizzling because we must make the AppDelegate conform to `UNUserNotificationCenterDelegate` and set the delegate for `UNUserNotificationCenter.current().delegate = self`.

Overall I’ve made everything work but there is some plumbing to do that is not specified in the documentation.

**Comment by mpodwysocki** [comment]
@twittemb It's an issue with our sample apps as they should be setting the delegate immediately during `application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`

**Comment by twittemb** [comment]
Thanks for the follow up. So I guess we can close this issue ? 

I think it could be nice to amend the README to reflect that, wouldn't it ?

**Comment by twittemb** [comment]
If I may, I think the Swift / SwiftUI sample apps should be updated also right ?

**Comment by mpodwysocki** [comment]
@twittemb they will be updated, just verifying through review that this is the correct approach before I merge the PR

**Comment by twittemb** [comment]
ok great, thanks.

For the issue https://github.com/Azure/azure-notificationhubs-ios/issues/101, Am I right when I must deactivate the method swizzling to access a User response to a notification with a category (with custom actions) ?

**Comment by mpodwysocki** [comment]
@twittemb you do not have to disable swizzling if you don't want to, no, as I show in my examples as I get the actions and save them to a variable as noted in the [AppDelegate](https://github.com/Azure/azure-notificationhubs-ios/blob/update-nh-sample/SampleNHAppSwift/SampleNHAppSwift/AppDelegate.swift#L69-L103)

**Comment by twittemb** [comment]
@mpodwysocki Hi,

Is there a way to register to the APNs for Provisional Push with the Azure NH SDK ?

Thanks.

**Comment by mpodwysocki** [comment]
@twittemb let's close this issue and please open a feature request for Provisional Push.
