### ISSUE TITLE
[QUERY] Handling categories does need swizzling being deactivated ?

### ISSUE THREAD

**Issue by twittemb** [Azure/azure-notificationhubs-ios#101]
**Query/Question**
I'm trying to implement notifications with "categories" and custom actions. Although I am able to catch them in my app, the `notificationHub(notificationHub:didReceiveNotification:)` delegate function does not provide the user's actions (we only have title, subtitle, body and userInfo in the MSNotificationHubMessage object).

Do we have to deactivated method swizzling and implement the `UNUserNotificationCenterDelegate` delegate functions to be able to retrieve the user's responses ?

***Why is this not a Bug or a feature Request?***
It could be a feature request depending on the relevance of the question.

**Setup (please complete the following information if applicable):**
 - OS: iOS 14
 - IDE : Xcode 12
 - Version of the Library used: 3.1.1
 - Swizzling is still activated
 - Token based authentication
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [x ] Setup information Added

**Comment by mpodwysocki** [comment]
@twittemb No, you do not have to deactivate the swizzling to handle this if you don't want to handle the calls as we show in our new samples
