### ISSUE TITLE
[Request] Azure-NotificationHubs CocoaPod

### ISSUE THREAD

**Issue by tomaskraina** [Azure/azure-notificationhubs-ios#11]
This would enable seamless version & dependency management in larger production-prospective projects.

This would be similar to what already exists for Microsoft Azure Mobile Services: https://cocoapods.org/pods/AzureSDK-iOS

**Comment by brannon** [comment]
It's super delayed, but we have published this SDK to CocoaPods now!

https://cocoapods.org/pods/AzureNotificationHubs-iOS
