### ISSUE TITLE
SwiftUI Previews in Xcode 14 not working while adding the WindowsAzureMessaging dependency

### ISSUE THREAD

**Issue by getangar** [Azure/azure-notificationhubs-ios#135]
**Describe the bug**
Xcode Version 14.1 (14B47b) is unable to generate the SwiftUI Preview when adding WindowsAzureMessaging (v3.1.5) reference from GitHub. 

***Exception or Stack Trace***
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x0000600001a52820):'WindowsAzureMessaging'>)

**To Reproduce**
1. Start Xcode Version 14.1 (14B47b)
2. Load a Project referencing from GitHub the WindowsAzureMessaging library
3. The project will build without errors
4. Open a fire containing a View
5. The SwiftUI preview fails with error

**Expected behavior**
I expect to see the preview of my SwiftUI view

**Screenshots**
![Xcode](https://user-images.githubusercontent.com/41167983/203015527-31c515b2-fc0c-49d1-b27e-b897edca28fb.jpg)

**Setup (please complete the following information):**
 - OS: macOS Ventura 13.0.1 (22A400)
 - IDE : Xcode Version 14.1 (14B47b)
 - WindowsAzureMessaging 3.1.5

**Additional context**
The issue I face seems to be similar to this: https://github.com/microsoft/appcenter-sdk-apple/pull/2433

**Comment by menteValidus** [comment]
Same problem happened with [AppCenter](https://github.com/microsoft/appcenter-sdk-apple/issues/2429) and they [fixed](https://github.com/microsoft/appcenter-sdk-apple/pull/2433/files) it. Hope these links will help to fix this problem.

**Comment by menteValidus** [comment]
Removing `type: .static` fixed problem for me, as I understand every package that contains it will fail previews. I'll create a PR and provide instructions how to fix it for your project until Azure team fixes it by themselves.

**Comment by menteValidus** [comment]
I'm really blind and didn't notice existing [PR](https://github.com/Azure/azure-notificationhubs-ios/pull/134). If someone wants a quick fix of this problem before Azure team will merge it just replace your azure dependency with `https://github.com/rafaelcalunga/azure-notificationhubs-ios` url and choose `main` branch.

**Comment by brannon** [comment]
Thanks @getangar and @menteValidus for the bug report. I added a comment to the related PR and was hoping you'd be willing to comment on it too:

https://github.com/Azure/azure-notificationhubs-ios/pull/134#issuecomment-1422015515

The TL;DR is: it looks like this has been resolved in Xcode 14.2. Could either of you confirm that is the case?

**Comment by rafaelcalunga** [comment]
Xcode 14.2 (14C18) solved this issue for my apps
