### ISSUE TITLE
iOS Rich push with mutable-content property

### ISSUE THREAD

**Issue by ArchForge** [Azure/azure-notificationhubs-ios#17]
Hi,
I'm trying to implement rich push notifications (with NotificationServiceExtension) for iOS(obj c), and I get a 400 error when sending the mutable-content property in the template with the method "registerTemplateWithDeviceToken". It might have some problem with the dash symbol (possibly). Does anyone know how to fix or work around this issue? Or if I'm way off somehow: what's the correct way to use the mutable-content property?

**Comment by jwargo** [comment]
Closing due to no response.
