### ISSUE TITLE
Bitcode is not full enabled

### ISSUE THREAD

**Issue by VicZhang1** [Azure/azure-notificationhubs-ios#23]
Hi,

I get an error as below:

> ld: bitcode bundle could not be generated because '/Users/Vic/projects/projecta/WindowsAzureMessaging.framework/WindowsAzureMessaging(SBNotificationHub.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/Vic/projects/projecta/WindowsAzureMessaging.framework/WindowsAzureMessaging' for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

But otool shows it contains bitcode:

> Vic:projecta Vic$ (otool -arch arm64 -l WindowsAzureMessaging.framework/WindowsAzureMessaging | grep LLVM) || echo "no bitcode"
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM

Any ideas?

Thanks,
-
Vic

**Comment by AnilKumar6270** [comment]
Guys I am getting the same error. Actually we have created on static library which will work for our company and added to Project for Enable Bit Code    **bitcode bundle could not be generated because**.    When I disable Bit Code I can archive successfully but I should give Bit code enable.

How do I solve this can any one help me.

**Comment by danielmillipede** [comment]
I had this issue with the Pod for v3.1.0, archiving with XCode 11.3.1.
I installed the package via Swift Package Manager, and that seemed to work.
