### ISSUE TITLE
Tags are not working properly for xamarin forms ios when I set enableTestSend to false

### ISSUE THREAD

**Issue by usman0910** [Azure/azure-notificationhubs-ios#29]
unable to send push notifications to specific tag on ios when I set enableTestSend to false in production, but if I send empty tag it works fine and also tags are working fine on android.

**Comment by jwargo** [comment]
@usman0910 Can you please be more specific?  You're telling us you can't send notifications, but there's not enough information for us to help you. Do you get an error message? Does the app not compile?

**Comment by jwargo** [comment]
Closing due to no response.
