### ISSUE TITLE
IOS 13.1.2 | Authorization Failed 401 | iOS 12.4.1 works | using latest build 2.0.4 AZFM

### ISSUE THREAD

**Issue by NateShaq** [Azure/azure-notificationhubs-ios#37]
On iOS 12.4.1 works perfectly. Upgraded Framework to latest build 2.0.4 AZURE MSG FMWK
On iOS 13.1.2 I run the same code and get a 401 error.

Any thoughts? Says token has expired in 13.1.2 every time. 
Tokens are correct and urls are correct. I think there is something wrong with the signing or time calculation. 

iOS XCODE Console Output. Changed some details.
URL:https://nsp1.servicebus.windows.net/hub1/Registrations/?$filter=deviceToken+eq+'C1DAAB...20B0F39631DFD8F'&api-version=2013-04

Headers:{
    Authorization = "SharedAccessSignature sr=http%3a%2f%2fnsp1.servicebus.windows.net%2fhub1%2fregistrations%2f%3f%24filter%3ddevicetoken%2beq%2b%27c1daab..b0f39631dfd8f%27%26api-version%3d2013-04&sig=eLeMSA6M9NB7BUm2%2FtDR1P%2Fana0HWwYe814bKxf6Obg%3D&se=1570779011&skn=Test";
    "Content-Type" = "application/xml";
    "User-Agent" = "NOTIFICATIONHUBS/2013-04(api-origin=IosSdk; os=iOS; os_version=13.1.2;)";
}

 Error registering for notifications: Error Domain=WindowsAzureMessaging Code=401 "URLRequest failed for <NSMutableURLRequest: 0x281b79960> { URL: https://nsp1.servicebus.windows.net/hub1/Registrations/?$filter=deviceToken+eq+'C1DAAB0...F39631DFD8F'&api-version=2013-04 } with status code: unauthorized" 

UserInfo={NSLocalizedDescription=URLRequest failed for <NSMutableURLRequest: 0x281b79960> { URL: https://nsp1.servicebus.windows.net/hub1/Registrations/?$filter=deviceToken+eq+'C1DAAB085473C0209C8...0F'&api-version=2013-04 } with status code: unauthorized}

Error registering for notifications: 401

**Comment by brannon** [comment]
@NateShaq there are no known issues with generating the Bearer token on iOS 13. I was just testing this today on both iOS 13.0 and iOS 13.1.3.

My guess is there is an issue with the expiry time in the token and the time on the server.

Are you still seeing this issue? If so you may need to submit a support request through the Azure Portal so that the team can take a look on the backend and help troubleshoot.

**Comment by NateShaq** [comment]
Brandon,

The issue was running Xcode 11.x on Mojave. 
After updating to Catalina + Xcode 11.2 Beta. The issue is not longer present.
In Xcode 11.1's release notes, I noticed that it was suppose to support Mojave, but don't waste your time. 

Nothing on the backend needed to change.

Thanks for the followup!

Nate

**Comment by brannon** [comment]
Thanks for the confirmation!
