### ISSUE TITLE
iOS 13 Consistent crash on unregisterAllWithDeviceToken

### ISSUE THREAD

**Issue by mlenarto** [Azure/azure-notificationhubs-ios#38]
Consistent crash when we call unregisterAllWithDeviceToken. 
- Using 2.0.4.
- Xcode 11.1
- iOS 13.1.3

Tried including the framework directly and through Cocoapods (not that it should make a difference).

Trace:
![Screen Shot 2019-10-22 at 2 43 47 PM](https://user-images.githubusercontent.com/2405919/67325241-79802580-f4da-11e9-9e5d-73c077813ef1.png)

Error in the console:
-[Swift.__StringStorage bytes]: unrecognized selector sent to instance 0x282536800

This is the only thing left that's blocking my team from updating from Xcode 10 to Xcode 11.

**Comment by AndreiMisiukevich** [comment]
@brannon hi,
Do you need any other information/samples for reproducing and fixing this issue?

Thanks

**Comment by mlenarto** [comment]
Yep, exactly @AndreiMisiukevich. We are passing a swift string casted as an NSData pointer, not actual NSData. Closing issue.

**Comment by brannon** [comment]
@mlenarto @AndreiMisiukevich Thanks for the follow-up. Were you always passing a Swift string cast to `NSData` ?

We did not intend to make any breaking changes, and from what I can tell by the code change on our side, it should not have been a breaking change.

**Comment by AndreiMisiukevich** [comment]
@brannon we passed Swift **String** (already escaped)

**Comment by vokal-isaac** [comment]
@brannon The old code only sent the `description` message to `deviceTokenData`, so it would have "worked" (not crashed) for any `NSObject *`, not just `NSData *` (and actually worked as long as `[deviceTokenData description]` could be reduced down to a hex string with the same transformations as `description` on an `NSData` instance).

The new code sends the `bytes` message to `deviceTokenData`, which only exists on some of the many things that responded to `description`.  If `deviceTokenData` actually is `NSData *` as declared in the interface, nothing breaks, but if someone typecast something else as `NSData *` before passing it in, it might have worked with the old code and broken with the new code.

**Comment by brannon** [comment]
Yeah, understood. But the type in the interface is `NSData*`.

I want to make sure we didn't making a breaking change. If someone chooses to ignore the interface declaration, and we change the implementation, that's not a breaking change.

The old code never should have used `description` to format the object anyway. This was bound to break at some point.
