### ISSUE TITLE
Question about tvOS support

### ISSUE THREAD

**Issue by szymonkalista** [Azure/azure-notificationhubs-ios#39]
Hello,

I'd like to use Azure's Notification Hub to send some notifications to the users that are using AppleTV.

Notifications on iOS are working great, but I can't use this package on tvOS.

Would it be possible to have a package made for tvOS?

**Comment by jwargo** [comment]
@szymonkalista this is not something currently on our roadmap as we haven't had a lot of requests for it. The best place to request features, and to get other customers to vote your suggested feature up, is to post it here: https://feedback.azure.com/forums/218849-notification-hubs.
