### ISSUE TITLE
Azure Notification HUB Tag having issue

### ISSUE THREAD

**Issue by prsreejith** [Azure/azure-notificationhubs-ios#41]
I want to use the email ID someone.user@abc.xy.com as Tag while registering Azure Notification Hub through my Xamarin iOS Project. 
I found that notification hub registration is working fine and sending push notification successfully from Azure Notification Hub Test send console also but it is not receiving on my iOS device at any state of the Application. As per my observation if the tag ( email id) having more than two period/dot(.) characters it will not receive push notification to your iOS device. Is it a limitation or a known issue  ?

It is working fine if I'm setting the Tag as  someone.user@abc.com
 
Environment
--------------------------------------------------
NuGet Package - Xamarin.Azure.NotificationHubs.iOS (2.0.4)

Xamarin.iOS
Version: 13.14.1.39 (Visual Studio Community)

Operating System
Mac OS X 10.15.4

Sample code is given below
----------------------------------------------------

string UserEmailID = "someone.user@abc.xy.com";

                    var tags = new NSSet(UserEmailID);
                        Hub.RegisterNative(deviceToken, tags, err =>
                        {
                            if (err != null)
                            {
                                Console.WriteLine("Error: " + err.DebugDescription);
                            }
                            else
                            {
                                Console.WriteLine("Success");
                            }
                        });

**Comment by brannon** [comment]
@prsreejith Thanks for the report, we'll investigate.

**Comment by mpodwysocki** [comment]
@prsreejith after working through this, we are unable to reproduce this bug.  Does this happen consistently?

**Comment by mpodwysocki** [comment]
Closing as per being inactive
