### ISSUE TITLE
bitcode support

### ISSUE THREAD

**Issue by 3bdev** [Azure/azure-notificationhubs-ios#91]
it seems missing bitcode support on 3.0.0. I got this error while archiving app.

**Comment by mpodwysocki** [comment]
@3bdev Can you provide your environment? What version of Xcode, and macOS?  I cannot reproduce this as we build our archives locally and it verifies just fine using `Scripts/build-archive.sh`

**Comment by mpodwysocki** [comment]
@3bdev can you try again with 3.0.1? https://github.com/Azure/azure-notificationhubs-ios/releases/tag/3.0.1

**Comment by 3bdev** [comment]
@mpodwysocki macos catalina 10.15.5 and xcode 11.6 anyway 3.0.1 is ok, thanks for your support.

**Comment by mpodwysocki** [comment]
Sorry about that @3bdev but glad we got it fixed for you
