### ISSUE TITLE
[BUG] Nested Register callback does not work when run on threadpool using Task.Run or Task.Factory.StartNew with any options combo

### ISSUE THREAD

**Issue by FrankSzendzielarz** [Azure/azure-notificationhubs-ios#95]
**Describe the bug**
Nested Register callback does not work when run on threadpool using Task.Run or Task.Factory.StartNew with any options combo

***Exception or Stack Trace***
None

**To Reproduce**
Please see [original issue](https://github.com/xamarin/xamarin-macios/issues/9213): 

***Code Snippet***
`public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {

            App.NotificationManager.SetRegistrationId(deviceToken);

            Task.Run(() => { 
            var test = new ConcurrentDictionary<string, int>();
            test.AddOrUpdate("test", 0, (x, y) => y);

            Hub.UnregisterAll(deviceToken, (errorC) =>
            {
                if (errorC != null)
                {
                    Debug.WriteLine($"Unable to call unregister {errorC}");
                    return;
                }

                try
                {

                    var tagsetLoud = new NSSet(test.Keys.ToArray());
                    var tagsetSilent = new NSSet(test.Keys.Append("silent").ToArray());

                    Hub.RegisterNative(deviceToken, tagsetLoud, (errorCallback) =>
                    {
                        if (errorCallback != null)
                        {

                        }
                        else
                        {

                        }
                    });

                    var templateExpiration = DateTime.Now.AddDays(120).ToString(System.Globalization.CultureInfo.CreateSpecificCulture("en-US"));
                    AppDelegate.Hub.RegisterTemplate(deviceToken, "defaultTemplate", AppConstants.APNTemplateBody, templateExpiration, tagsetLoud, (errorCallback) =>
                    {

                        if (errorCallback != null)
                        {

                        }

                    });

                }
                catch
                {
                    Debug.WriteLine("Failure registering");
                }
            });
        });

        }`

**Expected behavior**
Should register with notifications.

**Screenshots**
None.

**Setup (please complete the following information):**
 - OS: Mac Catalina build machine, Win 10 dev machine
 - IDE : VS Studio 2019 Community

**Additional context**
Callbacks not working correctly in xamarin ios / xamarin forms ios

**Comment by FrankSzendzielarz** [comment]
Sorry, no. This is now the third time this issue has been relocated. Can you (Azure/Xamarin) please take it upon yourselves to investigate the issue and assign it correctly? The platform does not work. A number of people have tried to raise the issue, and we're just getting bounced around. This is unacceptable.

**Comment by FrankSzendzielarz** [comment]
@mpodwysocki This is NOT an issue with XamarinComponents. This is an issue with SBNotificationHub and the register/unregister methods. If you are absolutely certain it is a Xamarin problem, please reply directly to your colleagues in the referenced original issue , who closed it and sent us here.

**Comment by mpodwysocki** [comment]
@FrankSzendzielarz for clarification, which version of the library are you using?

**Comment by mpodwysocki** [comment]
@FrankSzendzielarz can reproduce the issue as well even with the latest version and will sync with the results

**Comment by mpodwysocki** [comment]
@FrankSzendzielarz Yes, we are consolidating all of our Xamarin assets such as the Xamarin Forms and Xamarin.iOS, TVOS and MacOS support at [azure-notificationhubs-xamarin](https://github.com/Azure/azure-notificationhubs-xamarin)

**Comment by brannon** [comment]
Hi @FrankSzendzielarz, please take a look at the `MSNotificationHub` class when you get a chance. We recently rethought our approach for our iOS and Android SDKs and incorporated some of the simplicity of the App Center Push SDK. We think it's a much better programming model.

I would appreciate if you could point us to the Xamarin docs you were working from so we can make sure they are updated.

Moving forward, we will fix bugs in the `SBNotificationHub` implementation, but there will be no further feature work there. `MSNotificationHub` is the future.

Thanks!

**Comment by FrankSzendzielarz** [comment]
@monahan7 Adding you into the thread. Looks like there's a full fix here.

**Comment by FrankSzendzielarz** [comment]
@brannon thanks, will check it out. Will send you links to Xamarin docs too.

**Comment by monahan7** [comment]
[https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/webservices-azurenotificationhub/](https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/webservices-azurenotificationhub)

[https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub)

[https://docs.microsoft.com/en-us/azure/notification-hubs/xamarin-notification-hubs-ios-push-notification-apns-get-started](https://docs.microsoft.com/en-us/azure/notification-hubs/xamarin-notification-hubs-ios-push-notification-apns-get-started)


If you are a developer, and you google for instructions, you will be given many links, most out of date, that all use similar code to these. I am with FrankSzendzielarz, this is the first time I am hearing about MSNotificationHub. 

Google searches for help with azure notification hub and ios, do not take you to anything concerning MSNotificationHub. 

A search for MSNotificationHub gives me some links. I will apply your work around above, and then look into this.

**Comment by mpodwysocki** [comment]
@monahan7 I appreciate that, we will get those documents updated as soon as possible.  As noted, we have a Xamarin repository for all samples using the latest `MSNotificationHub` for iOS at [azure-notificaitonhubs-xamarin](https://github.com/Azure/azure-notificationhubs-xamarin)

**Comment by FrankSzendzielarz** [comment]
Concurring here with @monahan7, those were the links I'd been working off. Also, long threads running right up to a month or two ago discussing similar issues

 https://forums.xamarin.com/discussion/170901/xamarin-ios-cannot-register-with-azure-notification-hub-in-ios-13-1-2

More on SO.


I will add something there but I think it would be a good idea to follow these sorts of forums and direct users to the right place. The overall structure is a bit confusing.

**Comment by mpodwysocki** [comment]
@FrankSzendzielarz @monahan7 

We have confirmed this is an issue and a limitation with Apple.  This is the following reproduction code:
```objc
    SBNotificationHub* hub = [self getNotificationHub];
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [hub unregisterAllWithDeviceToken:deviceToken completion:^(NSError *error) {
            
            if (error) {
                NSLog(@"Error unregistering all with device token: %@", error);
                return;
            }
            
          // Comments this out causes the callback never to be run
            dispatch_async(dispatch_get_main_queue(), ^{
                [hub registerNativeWithDeviceToken:deviceToken tags:tags completion:^(NSError* error) {
                    // Never reaches here if the dispatch_async on the main thread doesn't happen
                    if (error != nil) {
                        NSLog(@"Error registering for notifications: %@", error);
                    } else {
                        dispatch_async(dispatch_get_main_queue(), ^{
                            [self showAlert:@"Registered" withTitle:@"Registration Status"];
                        });
                    }
                }];
            });
        }];
    });
```

If the `hub registerNativeWithDeviceToken:tags:completion:` is not called on the main thread, this will cause an issue with the initializing of the `NSURLConnection`.  We create the `NSURLConnection` via `initWithRequest:delegate` in the [`SBURLConnection`](https://github.com/Azure/azure-notificationhubs-ios/blob/main/WindowsAzureMessaging/WindowsAzureMessaging/Helpers/SBURLConnection.m#L40).  There is a large caveat as noted in the documentation for the `delegate` parameter, where I have highlighted the passage.  As noted in the text below, we must be on the default loop mode, which using `Task.Run` or `dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{}` don't currently do.

> The delegate object for the connection. The connection calls methods on this delegate as the load progresses. Delegate methods are called on the same thread that called this method. **By default, for the connection to work correctly, the calling thread’s run loop must be operating in the default run loop mode. See `scheduleInRunLoop:forMode:` to change the run loop and mode**

After consulting with the developer lead @brannon and with @mandel-macaque, it's best that we just note this in our documentation as a limitation and not try to fix it, otherwise causing some other threading issues.
